### ISSUE TITLE
IMGURL error in fillTables.sql

### ISSUE THREAD

**Issue by StahlErik** [pumpumba/Influsion-back-end#104]
![image](https://user-images.githubusercontent.com/22325129/48447481-4696c300-e79c-11e8-9732-92934a4b3282.png)

Something wrong with the INNER JOIN between IMGURLS and IPC. Might be a spelling error, the table is called IMGURL in createTables.SQLm and IMGURLS in fillTables.sql. However, I haven't found an exact solution locally.

**Comment by Filco306** [comment]
Fixed it now on branch database_setup

**Comment by Filco306** [comment]
Let me know if I should fix it on development and I'll do it in a jiffy
