### ISSUE TITLE
get_all_aggregate_influncers 

### ISSUE THREAD

**Issue by linneawsjogren** [pumpumba/Influsion-back-end#106]
We would love to get the following - 
ID - *Aggregate display name* - *tweet username* - *insta username * - *youtube username* - *profile pic url*
:)

**Comment by Filco306** [comment]
Pretty sure I already did this one

**Comment by Filco306** [comment]
you get this through get_all_info_infl. Would you like it with some specific input parameters?

**Comment by Filco306** [comment]
I checked it now, and I have two functions returning this information for you. 

1. /db/search_influencer. send in keywords that the user has searched for and the results will come up. 
2. /db/get_all_info_influencer. Send in influencer_id and (optional) post_platform. Will retrieve everything about an influencer. if you specify post_platform as twitter, instagram or youtube it will only fetch posts from this platform. if you do not specify, it will fetch all. Let me know if you would like to make influencer_id as optional parameter as well and I'll fix it.

**Comment by Filco306** [comment]
Not sure if they are integrated into master yet, I am awaiting pull requests to be reviewed and accepted by Elon and Ludwig

**Comment by codebyjonas** [comment]
Don't close this issue if it is not pushed to master.

**Comment by Filco306** [comment]
They are now I am pretty sure
