### ISSUE TITLE
deleteSucess: true is not shown

### ISSUE THREAD

**Issue by m-hakkestad** [pumpumba/Influsion-back-end#111]
deleteSucess: false is shown when a delete_user doesn't work but deleteSucess:true is not shown when a delete_user works. Is this something that could be done?

**Comment by Filco306** [comment]
Ye boi I fix

**Comment by Filco306** [comment]
Hmm, it should work. Let's check it out next time.

**Comment by m-hakkestad** [comment]
This is all the results I get in postman on a successfull delete:

"dbResults": {
        "usrid": 60,
        "usrname": "mack",
        "hashedpwd": "$2b$10$xu46.ueWpQnP2f4/evkmyOaks48f1QIi1nvnWw8.qUvuZhhGn1req",
        "email": "mack@gmail.com",
        "age": 45,
        "sex": "Male"
    }

**Comment by m-hakkestad** [comment]
Now delete_user returns this when user is deleted:

[
    {
        "command": "BEGIN",
        "rowCount": null,
        "oid": null,
        "rows": [],
        "fields": [],
        "_parsers": [],
        "RowCtor": null,
        "rowAsArray": false
    },
    {
        "command": "DELETE",
        "rowCount": 2,
        "oid": null,
        "rows": [],
        "fields": [],
        "_parsers": [],
        "RowCtor": null,
        "rowAsArray": false
    },
    {
        "command": "DELETE",
        "rowCount": 0,
        "oid": null,
        "rows": [],
        "fields": [],
        "_parsers": [],
        "RowCtor": null,
        "rowAsArray": false
    },
    {
        "command": "DELETE",
        "rowCount": 0,
        "oid": null,
        "rows": [],
        "fields": [],
        "_parsers": [],
        "RowCtor": null,
        "rowAsArray": false
    },
    {
        "command": "DELETE",
        "rowCount": 1,
        "oid": null,
        "rows": [],
        "fields": [],
        "_parsers": [],
        "RowCtor": null,
        "rowAsArray": false
    },
    {
        "command": "COMMIT",
        "rowCount": null,
        "oid": null,
        "rows": [],
        "fields": [],
        "_parsers": [],
        "RowCtor": null,
        "rowAsArray": false
    }
]

**Comment by Ludaestro** [comment]
Should be fixed in new version of development soon

**Comment by ElonB** [comment]
#158
