### ISSUE TITLE
Twitter aggregate call returns faulty jpeg images

### ISSUE THREAD

**Issue by codebyjonas** [pumpumba/Influsion-back-end#116]
You break the front-end when we want to get images that ends with jpeg. 

It should be `xyz.jpeg` **not** `xyz_jpeg`

**Comment by Ludaestro** [comment]
It's fixed, will be pushed into development soon

**Comment by codebyjonas** [comment]
When will it be in master?

**Comment by Ludaestro** [comment]
It's now in master
