### ISSUE TITLE
Build getAccountInformation for instagram

### ISSUE THREAD

**Issue by Ludaestro** [pumpumba/Influsion-back-end#121]
Filter the information like I have done for twitter below so that it can easily be inserted into database.
if(accountInformation.profile_image_url != undefined) {
var imageUrl = accountInformation.profile_image_url;
var n = imageUrl.lastIndexOf(".");
var fileType = imageUrl.substring(n, imageUrl.length);
imageUrl = imageUrl.substring(0, n - 7);
imageUrl = imageUrl + fileType;
}
var essentialInformation = {
"platform" : 'twitter',
"accountName" : accountInformation.screen_name,
"followersCount" : accountInformation.followers_count,
"createdAtUnixTime" : new Date(accountInformation.created_at).getTime(),
"accountUrl" : 'https://twitter.com/' + accountInformation.screen_name,
"imageUrl": imageUrl,
"verified": accountInformation.verified,
"platformContent": JSON.stringify(accountInformation)
};
return essentialInformation;

**Comment by TandiAB** [comment]
Through the instagram Graph API it is not possible to get information about when the account was created, neither is it possible to get a verfied status back.
What is the createdAt used for anyway..

**Comment by TandiAB** [comment]
This is now done as of version 1.4.0 of machinepack-instagramnodemachines2 except for the issues mentioned above

**Comment by Ludaestro** [comment]
The createdAt or verified Isn´t really that important, as long as we have the profile image it is okay. Good job! :)
