### ISSUE TITLE
Frontend wants profile image db/get_for_autosearch

### ISSUE THREAD

**Issue by codebyjonas** [pumpumba/Influsion-back-end#122]
We want a profile image returned from the `db/get_for_autosearch`call so we can show that in the search results.

**Comment by Filco306** [comment]
Fixed. Is on database_setup branch. Ask someone to make a pull request and you will get it

**Comment by codebyjonas** [comment]
This return `null` from deployed server.

**Comment by Filco306** [comment]
It is because no images have been inserted. #93

**Comment by Filco306** [comment]
This is done now
