### ISSUE TITLE
Update platfrom accounts - instagram, and search by user from aggregate/content crashes app

### ISSUE THREAD

**Issue by StahlErik** [pumpumba/Influsion-back-end#147]
![image](https://user-images.githubusercontent.com/22325129/49082981-86a17f80-f24b-11e8-92ff-7bb26796d447.png)

**Comment by Ludaestro** [comment]
dbFunction.getAdvertisementsFollowingFeed error should be fixed. Didn't test it enough before.

**Comment by TandiAB** [comment]
The update platform account account for instagram should work with version 1.6.0

**Comment by StahlErik** [comment]
I'll mark this as solved then
