### ISSUE TITLE
API Post to http://40.127.101.155/twitter/content does not return hashtags or media

### ISSUE THREAD

**Issue by codebyjonas** [pumpumba/Influsion-back-end#27]
![image](https://user-images.githubusercontent.com/6302670/46860584-0648cb80-ce11-11e8-919a-36f85d717e52.png)

**Comment by Ludaestro** [comment]
I solved it now, is a pending request to merge master now. I forgot to change the name to tweet_hashtags and tweet_media instead of hashtags and media.
