### ISSUE TITLE
Substring links in tweet_text

### ISSUE THREAD

**Issue by codebyjonas** [pumpumba/Influsion-back-end#28]
It is possible to substring and delete the links in `tweet_text` so it looks nice on the front-end. 

See picture: 
![image](https://user-images.githubusercontent.com/6302670/46860756-5e7fcd80-ce11-11e8-83b3-99cac6c887f9.png)

**Comment by Ludaestro** [comment]
I removed it in my version of new version of Twitter Cloud Component, is pending to merge with master.
