### ISSUE TITLE
Need status if user follows the current influencer or not, in every API

### ISSUE THREAD

**Issue by codebyjonas** [pumpumba/Influsion-back-end#30]

**Comment by Filco306** [comment]
In every API? Can't we just give you guys a list of all influencers a user follows?

**Comment by Filco306** [comment]
Fixed it for one API, we have to redo it on other places but I just managed to do it. Check /db/get_latest_posts

**Comment by Filco306** [comment]
Have fixed it for two APIs, /db/get_content_from_infl as well. We will keep it in mind in the future
