### ISSUE TITLE
Check if an account is TV operator or not

### ISSUE THREAD

**Issue by Ludaestro** [pumpumba/Influsion-back-end#58]
By sending query to database with username and password and then return true or false.

**Comment by Filco306** [comment]
They are two completely different tables, so this would be easy to check.

**Comment by Filco306** [comment]
I think this should be resolved in the front-end, with two separate logins

**Comment by Filco306** [comment]
I will be closing this now, since the login for the two are completely separate. I imagine they will have completely different UI:s and therefore it would not matter really.
