### ISSUE TITLE
Be able to retrieve user ID, preferably by using the login function? 

### ISSUE THREAD

**Issue by Ludaestro** [pumpumba/Influsion-back-end#60]
Right now I don't know how to retrieve it. I can use user ID as 1 at the moment though.

**Comment by codebyjonas** [comment]
If you log in, the user ID is returned. But that is maybe not the issue in this issue?

**Comment by Ludaestro** [comment]
I just get a true or false when I login. I'm using /db/login

**Comment by codebyjonas** [comment]
Strange, I get this when using `db/login`
![screenshot 2018-11-01 at 22 28 59](https://user-images.githubusercontent.com/6302670/47883624-9e8d0b80-de25-11e8-8db0-5c773f3ff0e1.png)

**Comment by Filco306** [comment]
The one jonas has is the latest one. Maybe you are not on the right branch Ludde? This is probably just a version handling issue

**Comment by Filco306** [comment]
I think it is because you changed it Ludwig! We can look at it together

**Comment by Ludaestro** [comment]
Oh, okay. Strange, I branched from development.

**Comment by Filco306** [comment]
I'll close this one now, I consider this solved
