### ISSUE TITLE
Insert information into platformaccount.

### ISSUE THREAD

**Issue by Filco306** [pumpumba/Influsion-back-end#93]
We need to fill the table platformaccount with information, like imgurl, profile link, description etc. I think one who has worked on each API should take this one and fetch information about youtubechannels, twitteraccounts and instagramaccounts and insert this information to the correct position.

I have developed a function, /db/update_platform_acc which creates a correct request based on post inputs. This should be modified and changed correctly for each API and then we can easily add information about each influencer's platform accounts

**Comment by Ludaestro** [comment]
Works for Youtube and Twitter, but not Instagram as we are waiting for a node machine to be developed.

**Comment by ElonB** [comment]
NodeMachine for instgram merged to dev 
#139

**Comment by ElonB** [comment]
#158
